In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('anime.csv')

In [11]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [13]:
df.shape

(50, 3)

In [78]:
df['Title'].head(7)

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
5    Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...
6    Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...
Name: Title, dtype: object

In [48]:
def extract_episodes(text):
    check = False;
    data = ""
    for i in text:
        if i == ')':
            break;
        if i == '(':
            check = True
            continue
        if check:
            data += i
    return data;

In [50]:
df["Epidoes"] = df["Title"].apply(extract_episodes)

In [64]:
df['Epidoes'] = df['Epidoes'].str.replace(' eps', "")

In [70]:
df['Epidoes'].astype(int)

0      64
1      24
2      13
3      51
4      10
5      51
6       1
7     148
8      13
9      13
10      2
11    110
12     13
13     13
14     12
15    201
16      1
17     22
18     24
19     25
20      1
21      1
22      7
23     14
24     74
25      1
26      1
27     12
28      1
29     24
30     23
31     12
32     26
33     13
34     16
35     11
36      1
37     11
38     10
39      1
40     26
41     12
42     75
43     26
44     26
45     24
46     10
47     12
48     12
49      4
Name: Epidoes, dtype: int64

In [72]:
df.head()

   Rank                                              Title  Score Epidoes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10

In [88]:
def extract_timestamp(txt):
    check = False
    ans = ""
    l = 0
    for i in txt:
        if i == ')':
            check = True;
            continue
        if check:
            ans += i;
            l += 1;
        if l == 19:
            return ans;
    return ans;

In [90]:
df['TimeLine'] = df["Title"].apply(extract_timestamp)

In [92]:
df["TimeLine"]

0     Apr 2009 - Jul 2010
1     Apr 2011 - Sep 2011
2     Oct 2022 - Dec 2022
3     Apr 2015 - Mar 2016
4     Apr 2019 - Jul 2019
5     Apr 2011 - Mar 2012
6     Jan 2021 - Jan 2021
7     Oct 2011 - Sep 2014
8     Apr 2022 - Jun 2022
9     Oct 2012 - Mar 2013
10    Mar 2023 - May 2023
11    Jan 1988 - Mar 1997
12    Jul 2023 - Aug 2023
13    Apr 2021 - Jun 2021
14    Jan 2017 - Mar 2017
15    Apr 2006 - Mar 2010
16    Sep 2016 - Sep 2016
17    Oct 2017 - Mar 2018
18    Oct 2008 - Mar 2009
19    Apr 2008 - Sep 2008
20    Jul 2013 - Jul 2013
21    Sep 2020 - Sep 2020
22    Aug 2017 - Aug 2017
23    Jul 2018 - Oct 2018
24    Apr 2004 - Sep 2005
25    Aug 2016 - Aug 2016
26    Dec 2022 - Dec 2022
27    Oct 2022 - Dec 2022
28    Dec 2022 - Dec 2022
29    Jan 2023 - Jun 2023
30    Jul 2023 - Aug 2023
31    Jan 2018 - Mar 2018
32    Apr 2020 - Oct 2021
33    Jan 2019 - Apr 2019
34    Dec 2020 - Mar 2021
35    Dec 2021 - Feb 2022
36    Jan 2017 - Jan 2017
37    Apr 2023 - Jun 2023
38    Oct 2016 - Dec 2016
39    Jul 2001 - Jul 2001
40    Jul 2013 - Dec 2013
41    Jan 2022 - Apr 2022
42    Oct 2000 - Mar 2002
43    Apr 1998 - Apr 1999
44    Apr 2022 - Oct 2022
45    Jul 2019 - Dec 2019
46    Oct 2014 - Dec 2014
47    Jan 2017 - Mar 2017
48    Oct 2022 - Dec 2022
49    Feb 1999 - Sep 1999
Name: TimeLine, dtype: object

In [94]:
df.head()

,Rank,Title,Score,Epidoes,TimeLine
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019