In [21]:
import numpy as numpy
import pandas as pd

In [22]:
data = {
    "Name": ["Hasnain", "Rahul", "Priya", "Aman"],
    "Age": [21, 22, 20, 23],
    "City": ["Dehradun", "Delhi", "Mumbai", "Bangalore"],
    "Salary": [45000, 55000, 40000, 60000]
}

In [23]:
df = pd.DataFrame(data)
df

      Name  Age       City  Salary
0  Hasnain   21   Dehradun   45000
1    Rahul   22      Delhi   55000
2    Priya   20     Mumbai   40000
3     Aman   23  Bangalore   60000

In [24]:
# creating dataframe from list

In [25]:
columns = ["Name", "Age", "City", "Salary"]

data1 = [
    ["Hasnain", 21, "Dehradun", 45000],
    ["Rahul", 22, "Delhi", 55000],
    ["Priya", 20, "Mumbai", 40000],
    ["Aman", 23, "Bangalore", 60000]
]

In [26]:
df1 = pd.DataFrame(data1,columns=columns)
df1

      Name  Age       City  Salary
0  Hasnain   21   Dehradun   45000
1    Rahul   22      Delhi   55000
2    Priya   20     Mumbai   40000
3     Aman   23  Bangalore   60000

## Indexing

In [35]:
df["Age"]

0    21
1    22
2    20
3    23
Name: Age, dtype: int64

In [41]:
df[["Age","Name"]]  # targetting multiple columns

   Age     Name
0   21  Hasnain
1   22    Rahul
2   20    Priya
3   23     Aman

In [47]:
# Adding a new ccolumn
df["Designation"] = ['Doc','Eng',"Doc","Eng"]

In [49]:
df

      Name  Age       City  Salary Designation
0  Hasnain   21   Dehradun   45000         Doc
1    Rahul   22      Delhi   55000         Eng
2    Priya   20     Mumbai   40000         Doc
3     Aman   23  Bangalore   60000         Eng

In [53]:
df.drop("Designation", axis=1)

      Name  Age       City  Salary
0  Hasnain   21   Dehradun   45000
1    Rahul   22      Delhi   55000
2    Priya   20     Mumbai   40000
3     Aman   23  Bangalore   60000

In [55]:
df

      Name  Age       City  Salary Designation
0  Hasnain   21   Dehradun   45000         Doc
1    Rahul   22      Delhi   55000         Eng
2    Priya   20     Mumbai   40000         Doc
3     Aman   23  Bangalore   60000         Eng

In [57]:
df.drop("Designation", axis=1, inplace=True)

In [59]:
df

      Name  Age       City  Salary
0  Hasnain   21   Dehradun   45000
1    Rahul   22      Delhi   55000
2    Priya   20     Mumbai   40000
3     Aman   23  Bangalore   60000

In [61]:
# selecting a row from DataFrame
df.loc[0]

Name       Hasnain
Age             21
City      Dehradun
Salary       45000
Name: 0, dtype: object

In [69]:
df.loc[0]

Name       Hasnain
Age             21
City      Dehradun
Salary       45000
Name: 0, dtype: object

In [71]:
df.loc[0,"Name"]

'Hasnain'

In [67]:
# selecting multiple rows from DataFrame
df.loc[[0,2]]

      Name  Age      City  Salary
0  Hasnain   21  Dehradun   45000
2    Priya   20    Mumbai   40000

In [73]:
df.iloc[3]

Name           Aman
Age              23
City      Bangalore
Salary        60000
Name: 3, dtype: object

In [75]:
# selecting subsets of rows and columns

In [79]:
# selecting first 2rows and ccolumns
df.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  Dehradun   45000
1     Delhi   55000

In [81]:
df[df['Age']>21]

    Name  Age       City  Salary
1  Rahul   22      Delhi   55000
3   Aman   23  Bangalore   60000

In [87]:
df[(df["Age"] > 21) & (df["City"] == "Bangalore")]

   Name  Age       City  Salary
3  Aman   23  Bangalore   60000

## Handling Missing Values

In [92]:
import pandas as pd
import numpy as np

data = [
    [1, "Hasnain", 21, "Dehradun", 45000, "Male"],
    [2, "Rahul", 22, "Delhi", 55000, "Male"],
    [3, "Priya", np.nan, "Mumbai", 40000, "Female"],
    [4, "Aman", 23, None, 60000, "Male"],
    [5, "Sneha", 21, "Bangalore", np.nan, "Female"],
    [6, None, 24, "Delhi", 52000, "Male"],
    [7, "Riya", np.nan, "Mumbai", 48000, "Female"],
    [8, "Arjun", 25, "Pune", 70000, None],
    [9, "Vikash", 22, "Delhi", 55000, "Male"],
    [10, "Neha", 20, "Mumbai", 35000, "Female"],
    [11, "Karan", 26, "Bangalore", 80000, "Male"],
    [12, "Anjali", 23, None, 62000, "Female"],
    [13, "Rohit", 27, "Delhi", np.nan, "Male"],
    [14, "Pooja", 22, "Mumbai", 45000, None],
    [15, "Sameer", 24, "Pune", 58000, "Male"],
    [16, "Meena", np.nan, "Delhi", 50000, "Female"],
    [17, "Arjun", 25, "Pune", 70000, "Male"],  # duplicate
    [18, "Raj", 21, "Delhi", -5000, "Male"],     # invalid salary
    [19, "Simran", 29, "Mumbai", 90000, "Female"],
    [20, "Aman", 23, "Delhi", 60000, "Male"],
]

columns = ["ID", "Name", "Age", "City", "Salary", "Gender"]

df = pd.DataFrame(data, columns=columns)

df

    ID     Name   Age       City   Salary  Gender
0    1  Hasnain  21.0   Dehradun  45000.0    Male
1    2    Rahul  22.0      Delhi  55000.0    Male
2    3    Priya   NaN     Mumbai  40000.0  Female
3    4     Aman  23.0       None  60000.0    Male
4    5    Sneha  21.0  Bangalore      NaN  Female
5    6     None  24.0      Delhi  52000.0    Male
6    7     Riya   NaN     Mumbai  48000.0  Female
7    8    Arjun  25.0       Pune  70000.0    None
8    9   Vikash  22.0      Delhi  55000.0    Male
9   10     Neha  20.0     Mumbai  35000.0  Female
10  11    Karan  26.0  Bangalore  80000.0    Male
11  12   Anjali  23.0       None  62000.0  Female
12  13    Rohit  27.0      Delhi      NaN    Male
13  14    Pooja  22.0     Mumbai  45000.0    None
14  15   Sameer  24.0       Pune  58000.0    Male
15  16    Meena   NaN      Delhi  50000.0  Female
16  17    Arjun  25.0       Pune  70000.0    Male
17  18      Raj  21.0      Delhi  -5000.0    Male
18  19   Simran  29.0     Mumbai  90000.0  Female
19  20     Aman  23.0      Delhi  60000.0    Male

## Missing Values

In [94]:
df.isnull().sum()

ID        0
Name      1
Age       3
City      2
Salary    2
Gender    2
dtype: int64

In [103]:
df.isnull()

       ID   Name    Age   City  Salary  Gender
0   False  False  False  False   False   False
1   False  False  False  False   False   False
2   False  False   True  False   False   False
3   False  False  False   True   False   False
4   False  False  False  False    True   False
5   False   True  False  False   False   False
6   False  False   True  False   False   False
7   False  False  False  False   False    True
8   False  False  False  False   False   False
9   False  False  False  False   False   False
10  False  False  False  False   False   False
11  False  False  False   True   False   False
12  False  False  False  False    True   False
13  False  False  False  False   False    True
14  False  False  False  False   False   False
15  False  False   True  False   False   False
16  False  False  False  False   False   False
17  False  False  False  False   False   False
18  False  False  False  False   False   False
19  False  False  False  False   False   False

In [111]:
# rows containing missing values
df.isnull().any(axis = 1)

0     False
1     False
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9     False
10    False
11     True
12     True
13     True
14    False
15     True
16    False
17    False
18    False
19    False
dtype: bool

In [109]:
# drop rows witg null values
df.dropna()

    ID     Name   Age       City   Salary  Gender
0    1  Hasnain  21.0   Dehradun  45000.0    Male
1    2    Rahul  22.0      Delhi  55000.0    Male
8    9   Vikash  22.0      Delhi  55000.0    Male
9   10     Neha  20.0     Mumbai  35000.0  Female
10  11    Karan  26.0  Bangalore  80000.0    Male
14  15   Sameer  24.0       Pune  58000.0    Male
16  17    Arjun  25.0       Pune  70000.0    Male
17  18      Raj  21.0      Delhi  -5000.0    Male
18  19   Simran  29.0     Mumbai  90000.0  Female
19  20     Aman  23.0      Delhi  60000.0    Male

In [113]:
# fill missing values
df["Age"].fillna(df["Age"].mean())

0     21.000000
1     22.000000
2     23.411765
3     23.000000
4     21.000000
5     24.000000
6     23.411765
7     25.000000
8     22.000000
9     20.000000
10    26.000000
11    23.000000
12    27.000000
13    22.000000
14    24.000000
15    23.411765
16    25.000000
17    21.000000
18    29.000000
19    23.000000
Name: Age, dtype: float64

In [117]:
# fill categorilcal nulls
df["City"].fillna("Unknown")

0      Dehradun
1         Delhi
2        Mumbai
3       Unknown
4     Bangalore
5         Delhi
6        Mumbai
7          Pune
8         Delhi
9        Mumbai
10    Bangalore
11      Unknown
12        Delhi
13       Mumbai
14         Pune
15        Delhi
16         Pune
17        Delhi
18       Mumbai
19        Delhi
Name: City, dtype: object

In [121]:
# find duplicates
df.duplicated()
# df[df.duplicated()]

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [123]:
df[df.duplicated()]

Empty DataFrame
Columns: [ID, Name, Age, City, Salary, Gender]
Index: []

In [125]:
# invalid values
df[df["Salary"] < 0]

    ID Name   Age   City  Salary Gender
17  18  Raj  21.0  Delhi -5000.0   Male

In [127]:
# replace invalid salaries
df.loc[df["Salary"] < 0, "Salary"] = np.nan

In [129]:
df["Salary"]

0     45000.0
1     55000.0
2     40000.0
3     60000.0
4         NaN
5     52000.0
6     48000.0
7     70000.0
8     55000.0
9     35000.0
10    80000.0
11    62000.0
12        NaN
13    45000.0
14    58000.0
15    50000.0
16    70000.0
17        NaN
18    90000.0
19    60000.0
Name: Salary, dtype: float64

In [131]:
df.describe()

             ID        Age        Salary
count  20.00000  17.000000     17.000000
mean   10.50000  23.411765  57352.941176
std     5.91608   2.399448  14190.406867
min     1.00000  20.000000  35000.000000
25%     5.75000  22.000000  48000.000000
50%    10.50000  23.000000  55000.000000
75%    15.25000  25.000000  62000.000000
max    20.00000  29.000000  90000.000000

In [133]:
# value counts
df["Gender"].value_counts()

Gender
Male      11
Female     7
Name: count, dtype: int64

In [135]:
df["City"].value_counts()

City
Delhi        7
Mumbai       5
Pune         3
Bangalore    2
Dehradun     1
Name: count, dtype: int64

In [137]:
df[(df["Age"] > 22) & (df["Salary"] > 50000)]

    ID    Name   Age       City   Salary  Gender
3    4    Aman  23.0       None  60000.0    Male
5    6    None  24.0      Delhi  52000.0    Male
7    8   Arjun  25.0       Pune  70000.0    None
10  11   Karan  26.0  Bangalore  80000.0    Male
11  12  Anjali  23.0       None  62000.0  Female
14  15  Sameer  24.0       Pune  58000.0    Male
16  17   Arjun  25.0       Pune  70000.0    Male
18  19  Simran  29.0     Mumbai  90000.0  Female
19  20    Aman  23.0      Delhi  60000.0    Male