In [1]:
import pandas as pd
import numpy as np

data = [
    [1, "Hasnain", 21, "Delhi", 45000, "Male", "Yes"],
    [2, "Rahul", 22, "Mumbai", 55000, "Male", "No"],
    [3, "Priya", np.nan, "Delhi", 40000, "Female", "Yes"],
    [4, "Aman", 23, None, 60000, "Male", "Yes"],
    [5, "Sneha", 21, "Bangalore", np.nan, "Female", "No"],
    [6, None, 24, "Delhi", 52000, "Male", "Yes"],
    [7, "Riya", np.nan, "Mumbai", 48000, "Female", "Yes"],
    [8, "Arjun", 25, "Pune", 70000, None, "No"],
    [9, "Vikash", 22, "Delhi", 55000, "Male", "Yes"],
    [10, "Neha", 20, "Mumbai", 35000, "Female", "No"],
    [11, "Karan", 26, "Bangalore", 80000, "Male", "Yes"],
    [12, "Anjali", 23, None, 62000, "Female", "Yes"],
    [13, "Rohit", 27, "Delhi", np.nan, "Male", "No"],
    [14, "Pooja", 22, "Mumbai", 45000, None, "Yes"],
    [15, "Sameer", 24, "Pune", 58000, "Male", "No"],
    [16, "Meena", np.nan, "Delhi", 50000, "Female", "Yes"],
    [17, "Arjun", 25, "Pune", 70000, "Male", "No"],
    [17, "Arjun", 25, "Pune", 70000, "Male", "No"],
    [18, "Raj", 21, "Delhi", -5000, "Male", "Yes"],
    [19, "Simran", 29, "Mumbai", 90000, "Female", "Yes"],
    [20, "Aman", 23, "Delhi", 60000, "Male", "Yes"],
    [21, "Kabir", 35, "Delhi", 120000, "Male", "No"],
    [22, "Nisha", 19, "Mumbai", 25000, "Female", "Yes"],
    [23, "Ravi", 22, "Delhi", 55000, "M", "Yes"],
    [24, "Pinky", 24, "Mumbai", 60000, "F", "No"],
    [25, "Mohit", -2, "Pune", 45000, "Male", "Yes"],
    [26, "Sara", 21, "Delhi", 48000, "Female", None],
    [27, "Dev", 28, "Bangalore", 75000, "Male", "Yes"],
    [28, "Isha", 22, "Delhi", 50000, "Female", "No"],
    [29, "Rohan", 23, "Mumbai", 55000, "Male", "Yes"],
    [30, "Kriti", 21, "Bangalore", 65000, "Female", "Yes"],
]

columns = [
    "ID",
    "Name",
    "Age",
    "City",
    "Salary",
    "Gender",
    "Remote"
]

df = pd.DataFrame(data, columns=columns)

In [3]:
df

    ID     Name   Age       City    Salary  Gender Remote
0    1  Hasnain  21.0      Delhi   45000.0    Male    Yes
1    2    Rahul  22.0     Mumbai   55000.0    Male     No
2    3    Priya   NaN      Delhi   40000.0  Female    Yes
3    4     Aman  23.0       None   60000.0    Male    Yes
4    5    Sneha  21.0  Bangalore       NaN  Female     No
5    6     None  24.0      Delhi   52000.0    Male    Yes
6    7     Riya   NaN     Mumbai   48000.0  Female    Yes
7    8    Arjun  25.0       Pune   70000.0    None     No
8    9   Vikash  22.0      Delhi   55000.0    Male    Yes
9   10     Neha  20.0     Mumbai   35000.0  Female     No
10  11    Karan  26.0  Bangalore   80000.0    Male    Yes
11  12   Anjali  23.0       None   62000.0  Female    Yes
12  13    Rohit  27.0      Delhi       NaN    Male     No
13  14    Pooja  22.0     Mumbai   45000.0    None    Yes
14  15   Sameer  24.0       Pune   58000.0    Male     No
15  16    Meena   NaN      Delhi   50000.0  Female    Yes
16  17    Arjun  25.0       Pune   70000.0    Male     No
17  17    Arjun  25.0       Pune   70000.0    Male     No
18  18      Raj  21.0      Delhi   -5000.0    Male    Yes
19  19   Simran  29.0     Mumbai   90000.0  Female    Yes
20  20     Aman  23.0      Delhi   60000.0    Male    Yes
21  21    Kabir  35.0      Delhi  120000.0    Male     No
22  22    Nisha  19.0     Mumbai   25000.0  Female    Yes
23  23     Ravi  22.0      Delhi   55000.0       M    Yes
24  24    Pinky  24.0     Mumbai   60000.0       F     No
25  25    Mohit  -2.0       Pune   45000.0    Male    Yes
26  26     Sara  21.0      Delhi   48000.0  Female   None
27  27      Dev  28.0  Bangalore   75000.0    Male    Yes
28  28     Isha  22.0      Delhi   50000.0  Female     No
29  29    Rohan  23.0     Mumbai   55000.0    Male    Yes
30  30    Kriti  21.0  Bangalore   65000.0  Female    Yes

In [5]:
df.count()

ID        31
Name      30
Age       28
City      29
Salary    29
Gender    29
Remote    30
dtype: int64

In [7]:
df.describe()

              ID        Age         Salary
count  31.000000  28.000000      29.000000
mean   15.548387  22.714286   56482.758621
std     8.659633   5.830044   21465.288740
min     1.000000  -2.000000   -5000.000000
25%     8.500000  21.000000   48000.000000
50%    16.000000  23.000000   55000.000000
75%    22.500000  25.000000   65000.000000
max    30.000000  35.000000  120000.000000

In [9]:
df.head()

   ID     Name   Age       City   Salary  Gender Remote
0   1  Hasnain  21.0      Delhi  45000.0    Male    Yes
1   2    Rahul  22.0     Mumbai  55000.0    Male     No
2   3    Priya   NaN      Delhi  40000.0  Female    Yes
3   4     Aman  23.0       None  60000.0    Male    Yes
4   5    Sneha  21.0  Bangalore      NaN  Female     No

In [11]:
df.tail()

    ID   Name   Age       City   Salary  Gender Remote
26  26   Sara  21.0      Delhi  48000.0  Female   None
27  27    Dev  28.0  Bangalore  75000.0    Male    Yes
28  28   Isha  22.0      Delhi  50000.0  Female     No
29  29  Rohan  23.0     Mumbai  55000.0    Male    Yes
30  30  Kriti  21.0  Bangalore  65000.0  Female    Yes

In [15]:
df["City"].value_counts()

City
Delhi        12
Mumbai        8
Pune          5
Bangalore     4
Name: count, dtype: int64

In [25]:
df.isnull().any(axis=0)

ID        False
Name       True
Age        True
City       True
Salary     True
Gender     True
Remote     True
dtype: bool

In [27]:
df.isnull().any(axis=1)

0     False
1     False
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9     False
10    False
11     True
12     True
13     True
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30    False
dtype: bool

In [29]:
df['Age'].fillna(df["Age"].mean())

0     21.000000
1     22.000000
2     22.714286
3     23.000000
4     21.000000
5     24.000000
6     22.714286
7     25.000000
8     22.000000
9     20.000000
10    26.000000
11    23.000000
12    27.000000
13    22.000000
14    24.000000
15    22.714286
16    25.000000
17    25.000000
18    21.000000
19    29.000000
20    23.000000
21    35.000000
22    19.000000
23    22.000000
24    24.000000
25    -2.000000
26    21.000000
27    28.000000
28    22.000000
29    23.000000
30    21.000000
Name: Age, dtype: float64

In [31]:
df['City'].fillna("Unkown")

0         Delhi
1        Mumbai
2         Delhi
3        Unkown
4     Bangalore
5         Delhi
6        Mumbai
7          Pune
8         Delhi
9        Mumbai
10    Bangalore
11       Unkown
12        Delhi
13       Mumbai
14         Pune
15        Delhi
16         Pune
17         Pune
18        Delhi
19       Mumbai
20        Delhi
21        Delhi
22       Mumbai
23        Delhi
24       Mumbai
25         Pune
26        Delhi
27    Bangalore
28        Delhi
29       Mumbai
30    Bangalore
Name: City, dtype: object

In [33]:
df['Gender'].fillna("Unkown")

0       Male
1       Male
2     Female
3       Male
4     Female
5       Male
6     Female
7     Unkown
8       Male
9     Female
10      Male
11    Female
12      Male
13    Unkown
14      Male
15    Female
16      Male
17      Male
18      Male
19    Female
20      Male
21      Male
22    Female
23         M
24         F
25      Male
26    Female
27      Male
28    Female
29      Male
30    Female
Name: Gender, dtype: object

In [35]:
df[df["Age"] > 25]

    ID    Name   Age       City    Salary  Gender Remote
10  11   Karan  26.0  Bangalore   80000.0    Male    Yes
12  13   Rohit  27.0      Delhi       NaN    Male     No
19  19  Simran  29.0     Mumbai   90000.0  Female    Yes
21  21   Kabir  35.0      Delhi  120000.0    Male     No
27  27     Dev  28.0  Bangalore   75000.0    Male    Yes

In [37]:
df[df['City'] == "Delhi"]

    ID     Name   Age   City    Salary  Gender Remote
0    1  Hasnain  21.0  Delhi   45000.0    Male    Yes
2    3    Priya   NaN  Delhi   40000.0  Female    Yes
5    6     None  24.0  Delhi   52000.0    Male    Yes
8    9   Vikash  22.0  Delhi   55000.0    Male    Yes
12  13    Rohit  27.0  Delhi       NaN    Male     No
15  16    Meena   NaN  Delhi   50000.0  Female    Yes
18  18      Raj  21.0  Delhi   -5000.0    Male    Yes
20  20     Aman  23.0  Delhi   60000.0    Male    Yes
21  21    Kabir  35.0  Delhi  120000.0    Male     No
23  23     Ravi  22.0  Delhi   55000.0       M    Yes
26  26     Sara  21.0  Delhi   48000.0  Female   None
28  28     Isha  22.0  Delhi   50000.0  Female     No

In [39]:
df[(df['City'] == "Delhi") & (df["Salary"] > 50000)]

    ID    Name   Age   City    Salary Gender Remote
5    6    None  24.0  Delhi   52000.0   Male    Yes
8    9  Vikash  22.0  Delhi   55000.0   Male    Yes
20  20    Aman  23.0  Delhi   60000.0   Male    Yes
21  21   Kabir  35.0  Delhi  120000.0   Male     No
23  23    Ravi  22.0  Delhi   55000.0      M    Yes

In [43]:
df[(df['City'] == "Delhi") | (df['City'] == "Mumbai")]

    ID     Name   Age    City    Salary  Gender Remote
0    1  Hasnain  21.0   Delhi   45000.0    Male    Yes
1    2    Rahul  22.0  Mumbai   55000.0    Male     No
2    3    Priya   NaN   Delhi   40000.0  Female    Yes
5    6     None  24.0   Delhi   52000.0    Male    Yes
6    7     Riya   NaN  Mumbai   48000.0  Female    Yes
8    9   Vikash  22.0   Delhi   55000.0    Male    Yes
9   10     Neha  20.0  Mumbai   35000.0  Female     No
12  13    Rohit  27.0   Delhi       NaN    Male     No
13  14    Pooja  22.0  Mumbai   45000.0    None    Yes
15  16    Meena   NaN   Delhi   50000.0  Female    Yes
18  18      Raj  21.0   Delhi   -5000.0    Male    Yes
19  19   Simran  29.0  Mumbai   90000.0  Female    Yes
20  20     Aman  23.0   Delhi   60000.0    Male    Yes
21  21    Kabir  35.0   Delhi  120000.0    Male     No
22  22    Nisha  19.0  Mumbai   25000.0  Female    Yes
23  23     Ravi  22.0   Delhi   55000.0       M    Yes
24  24    Pinky  24.0  Mumbai   60000.0       F     No
26  26     Sara  21.0   Delhi   48000.0  Female   None
28  28     Isha  22.0   Delhi   50000.0  Female     No
29  29    Rohan  23.0  Mumbai   55000.0    Male    Yes

In [45]:
df[df["City"] != "Delhi"]

    ID    Name   Age       City   Salary  Gender Remote
1    2   Rahul  22.0     Mumbai  55000.0    Male     No
3    4    Aman  23.0       None  60000.0    Male    Yes
4    5   Sneha  21.0  Bangalore      NaN  Female     No
6    7    Riya   NaN     Mumbai  48000.0  Female    Yes
7    8   Arjun  25.0       Pune  70000.0    None     No
9   10    Neha  20.0     Mumbai  35000.0  Female     No
10  11   Karan  26.0  Bangalore  80000.0    Male    Yes
11  12  Anjali  23.0       None  62000.0  Female    Yes
13  14   Pooja  22.0     Mumbai  45000.0    None    Yes
14  15  Sameer  24.0       Pune  58000.0    Male     No
16  17   Arjun  25.0       Pune  70000.0    Male     No
17  17   Arjun  25.0       Pune  70000.0    Male     No
19  19  Simran  29.0     Mumbai  90000.0  Female    Yes
22  22   Nisha  19.0     Mumbai  25000.0  Female    Yes
24  24   Pinky  24.0     Mumbai  60000.0       F     No
25  25   Mohit  -2.0       Pune  45000.0    Male    Yes
27  27     Dev  28.0  Bangalore  75000.0    Male    Yes
29  29   Rohan  23.0     Mumbai  55000.0    Male    Yes
30  30   Kriti  21.0  Bangalore  65000.0  Female    Yes

In [47]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
dtype: bool

In [51]:
df.duplicated().sum()

1

In [53]:
df["ID"].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: ID, dtype: bool

In [55]:
df[df["Salary"] < 0]

    ID Name   Age   City  Salary Gender Remote
18  18  Raj  21.0  Delhi -5000.0   Male    Yes

In [57]:
df[df["Age"] < 0]

    ID   Name  Age  City   Salary Gender Remote
25  25  Mohit -2.0  Pune  45000.0   Male    Yes

In [59]:
df[df["Salary"] < 0] = np.NaN

In [61]:
df["Salary"]

0      45000.0
1      55000.0
2      40000.0
3      60000.0
4          NaN
5      52000.0
6      48000.0
7      70000.0
8      55000.0
9      35000.0
10     80000.0
11     62000.0
12         NaN
13     45000.0
14     58000.0
15     50000.0
16     70000.0
17     70000.0
18         NaN
19     90000.0
20     60000.0
21    120000.0
22     25000.0
23     55000.0
24     60000.0
25     45000.0
26     48000.0
27     75000.0
28     50000.0
29     55000.0
30     65000.0
Name: Salary, dtype: float64

In [63]:
df[df["Age"] < 0] = np.NaN

In [69]:
df.fillna(df["Salary"].median())

         ID     Name      Age       City    Salary   Gender   Remote
0       1.0  Hasnain     21.0      Delhi   45000.0     Male      Yes
1       2.0    Rahul     22.0     Mumbai   55000.0     Male       No
2       3.0    Priya  55000.0      Delhi   40000.0   Female      Yes
3       4.0     Aman     23.0    55000.0   60000.0     Male      Yes
4       5.0    Sneha     21.0  Bangalore   55000.0   Female       No
5       6.0  55000.0     24.0      Delhi   52000.0     Male      Yes
6       7.0     Riya  55000.0     Mumbai   48000.0   Female      Yes
7       8.0    Arjun     25.0       Pune   70000.0  55000.0       No
8       9.0   Vikash     22.0      Delhi   55000.0     Male      Yes
9      10.0     Neha     20.0     Mumbai   35000.0   Female       No
10     11.0    Karan     26.0  Bangalore   80000.0     Male      Yes
11     12.0   Anjali     23.0    55000.0   62000.0   Female      Yes
12     13.0    Rohit     27.0      Delhi   55000.0     Male       No
13     14.0    Pooja     22.0     Mumbai   45000.0  55000.0      Yes
14     15.0   Sameer     24.0       Pune   58000.0     Male       No
15     16.0    Meena  55000.0      Delhi   50000.0   Female      Yes
16     17.0    Arjun     25.0       Pune   70000.0     Male       No
17     17.0    Arjun     25.0       Pune   70000.0     Male       No
18  55000.0  55000.0  55000.0    55000.0   55000.0  55000.0  55000.0
19     19.0   Simran     29.0     Mumbai   90000.0   Female      Yes
20     20.0     Aman     23.0      Delhi   60000.0     Male      Yes
21     21.0    Kabir     35.0      Delhi  120000.0     Male       No
22     22.0    Nisha     19.0     Mumbai   25000.0   Female      Yes
23     23.0     Ravi     22.0      Delhi   55000.0        M      Yes
24     24.0    Pinky     24.0     Mumbai   60000.0        F       No
25  55000.0  55000.0  55000.0    55000.0   55000.0  55000.0  55000.0
26     26.0     Sara     21.0      Delhi   48000.0   Female  55000.0
27     27.0      Dev     28.0  Bangalore   75000.0     Male      Yes
28     28.0     Isha     22.0      Delhi   50000.0   Female       No
29     29.0    Rohan     23.0     Mumbai   55000.0     Male      Yes
30     30.0    Kriti     21.0  Bangalore   65000.0   Female      Yes

In [73]:
df["Annual Salary"] = df["Salary"] * 12

In [75]:
df

      ID     Name   Age       City    Salary  Gender Remote  Annual Salary
0    1.0  Hasnain  21.0      Delhi   45000.0    Male    Yes       540000.0
1    2.0    Rahul  22.0     Mumbai   55000.0    Male     No       660000.0
2    3.0    Priya   NaN      Delhi   40000.0  Female    Yes       480000.0
3    4.0     Aman  23.0       None   60000.0    Male    Yes       720000.0
4    5.0    Sneha  21.0  Bangalore       NaN  Female     No            NaN
5    6.0     None  24.0      Delhi   52000.0    Male    Yes       624000.0
6    7.0     Riya   NaN     Mumbai   48000.0  Female    Yes       576000.0
7    8.0    Arjun  25.0       Pune   70000.0    None     No       840000.0
8    9.0   Vikash  22.0      Delhi   55000.0    Male    Yes       660000.0
9   10.0     Neha  20.0     Mumbai   35000.0  Female     No       420000.0
10  11.0    Karan  26.0  Bangalore   80000.0    Male    Yes       960000.0
11  12.0   Anjali  23.0       None   62000.0  Female    Yes       744000.0
12  13.0    Rohit  27.0      Delhi       NaN    Male     No            NaN
13  14.0    Pooja  22.0     Mumbai   45000.0    None    Yes       540000.0
14  15.0   Sameer  24.0       Pune   58000.0    Male     No       696000.0
15  16.0    Meena   NaN      Delhi   50000.0  Female    Yes       600000.0
16  17.0    Arjun  25.0       Pune   70000.0    Male     No       840000.0
17  17.0    Arjun  25.0       Pune   70000.0    Male     No       840000.0
18   NaN      NaN   NaN        NaN       NaN     NaN    NaN            NaN
19  19.0   Simran  29.0     Mumbai   90000.0  Female    Yes      1080000.0
20  20.0     Aman  23.0      Delhi   60000.0    Male    Yes       720000.0
21  21.0    Kabir  35.0      Delhi  120000.0    Male     No      1440000.0
22  22.0    Nisha  19.0     Mumbai   25000.0  Female    Yes       300000.0
23  23.0     Ravi  22.0      Delhi   55000.0       M    Yes       660000.0
24  24.0    Pinky  24.0     Mumbai   60000.0       F     No       720000.0
25   NaN      NaN   NaN        NaN       NaN     NaN    NaN            NaN
26  26.0     Sara  21.0      Delhi   48000.0  Female   None       576000.0
27  27.0      Dev  28.0  Bangalore   75000.0    Male    Yes       900000.0
28  28.0     Isha  22.0      Delhi   50000.0  Female     No       600000.0
29  29.0    Rohan  23.0     Mumbai   55000.0    Male    Yes       660000.0
30  30.0    Kriti  21.0  Bangalore   65000.0  Female    Yes       780000.0

## Real Solution

In [82]:
import pandas as pd
import numpy as np

# ============================================================
# DATASET
# ============================================================

data = [
    [1, "Hasnain", 21, "Delhi", 45000, "Male", "Yes"],
    [2, "Rahul", 22, "Mumbai", 55000, "Male", "No"],
    [3, "Priya", np.nan, "Delhi", 40000, "Female", "Yes"],
    [4, "Aman", 23, None, 60000, "Male", "Yes"],
    [5, "Sneha", 21, "Bangalore", np.nan, "Female", "No"],
    [6, None, 24, "Delhi", 52000, "Male", "Yes"],
    [7, "Riya", np.nan, "Mumbai", 48000, "Female", "Yes"],
    [8, "Arjun", 25, "Pune", 70000, None, "No"],
    [9, "Vikash", 22, "Delhi", 55000, "Male", "Yes"],
    [10, "Neha", 20, "Mumbai", 35000, "Female", "No"],
    [11, "Karan", 26, "Bangalore", 80000, "Male", "Yes"],
    [12, "Anjali", 23, None, 62000, "Female", "Yes"],
    [13, "Rohit", 27, "Delhi", np.nan, "Male", "No"],
    [14, "Pooja", 22, "Mumbai", 45000, None, "Yes"],
    [15, "Sameer", 24, "Pune", 58000, "Male", "No"],
    [16, "Meena", np.nan, "Delhi", 50000, "Female", "Yes"],
    [17, "Arjun", 25, "Pune", 70000, "Male", "No"],
    [17, "Arjun", 25, "Pune", 70000, "Male", "No"],
    [18, "Raj", 21, "Delhi", -5000, "Male", "Yes"],
    [19, "Simran", 29, "Mumbai", 90000, "Female", "Yes"],
    [20, "Aman", 23, "Delhi", 60000, "Male", "Yes"],
    [21, "Kabir", 35, "Delhi", 120000, "Male", "No"],
    [22, "Nisha", 19, "Mumbai", 25000, "Female", "Yes"],
    [23, "Ravi", 22, "Delhi", 55000, "M", "Yes"],
    [24, "Pinky", 24, "Mumbai", 60000, "F", "No"],
    [25, "Mohit", -2, "Pune", 45000, "Male", "Yes"],
    [26, "Sara", 21, "Delhi", 48000, "Female", None],
    [27, "Dev", 28, "Bangalore", 75000, "Male", "Yes"],
    [28, "Isha", 22, "Delhi", 50000, "Female", "No"],
    [29, "Rohan", 23, "Mumbai", 55000, "Male", "Yes"],
    [30, "Kriti", 21, "Bangalore", 65000, "Female", "Yes"],
]

columns = ["ID", "Name", "Age", "City", "Salary", "Gender", "Remote"]

df = pd.DataFrame(data, columns=columns)
df

    ID     Name   Age       City    Salary  Gender Remote
0    1  Hasnain  21.0      Delhi   45000.0    Male    Yes
1    2    Rahul  22.0     Mumbai   55000.0    Male     No
2    3    Priya   NaN      Delhi   40000.0  Female    Yes
3    4     Aman  23.0       None   60000.0    Male    Yes
4    5    Sneha  21.0  Bangalore       NaN  Female     No
5    6     None  24.0      Delhi   52000.0    Male    Yes
6    7     Riya   NaN     Mumbai   48000.0  Female    Yes
7    8    Arjun  25.0       Pune   70000.0    None     No
8    9   Vikash  22.0      Delhi   55000.0    Male    Yes
9   10     Neha  20.0     Mumbai   35000.0  Female     No
10  11    Karan  26.0  Bangalore   80000.0    Male    Yes
11  12   Anjali  23.0       None   62000.0  Female    Yes
12  13    Rohit  27.0      Delhi       NaN    Male     No
13  14    Pooja  22.0     Mumbai   45000.0    None    Yes
14  15   Sameer  24.0       Pune   58000.0    Male     No
15  16    Meena   NaN      Delhi   50000.0  Female    Yes
16  17    Arjun  25.0       Pune   70000.0    Male     No
17  17    Arjun  25.0       Pune   70000.0    Male     No
18  18      Raj  21.0      Delhi   -5000.0    Male    Yes
19  19   Simran  29.0     Mumbai   90000.0  Female    Yes
20  20     Aman  23.0      Delhi   60000.0    Male    Yes
21  21    Kabir  35.0      Delhi  120000.0    Male     No
22  22    Nisha  19.0     Mumbai   25000.0  Female    Yes
23  23     Ravi  22.0      Delhi   55000.0       M    Yes
24  24    Pinky  24.0     Mumbai   60000.0       F     No
25  25    Mohit  -2.0       Pune   45000.0    Male    Yes
26  26     Sara  21.0      Delhi   48000.0  Female   None
27  27      Dev  28.0  Bangalore   75000.0    Male    Yes
28  28     Isha  22.0      Delhi   50000.0  Female     No
29  29    Rohan  23.0     Mumbai   55000.0    Male    Yes
30  30    Kriti  21.0  Bangalore   65000.0  Female    Yes

### Level 1 — Inspection

In [103]:
# Q1. Number of rows and columns
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
print('-'*70)

# Q2. First 5 rows
print(df.head())
print('-'*70)


# Q3. Last 5 rows
print(df.tail())
print('-'*70)


# Q4. Data types
print(df.dtypes)
print('-'*70)


# Q5. Statistical summary
print(df.describe())
print('-'*70)


# Q6. Number of unique cities
print(f"Number of Unique cities: {df['City'].nunique()}")
print('-'*70)


# Q7. Unique cities
print(df["City"].unique())
print('-'*70)


# Q8. Number of employees in each city
print("Numbr of employees in each city\n",df["City"].value_counts())
print('-'*70)

Rows: 31
Columns: 7
----------------------------------------------------------------------
   ID     Name   Age       City   Salary  Gender Remote
0   1  Hasnain  21.0      Delhi  45000.0    Male    Yes
1   2    Rahul  22.0     Mumbai  55000.0    Male     No
2   3    Priya   NaN      Delhi  40000.0  Female    Yes
3   4     Aman  23.0       None  60000.0    Male    Yes
4   5    Sneha  21.0  Bangalore      NaN  Female     No
----------------------------------------------------------------------
    ID   Name   Age       City   Salary  Gender Remote
26  26   Sara  21.0      Delhi  48000.0  Female   None
27  27    Dev  28.0  Bangalore  75000.0    Male    Yes
28  28   Isha  22.0      Delhi  50000.0  Female     No
29  29  Rohan  23.0     Mumbai  55000.0    Male    Yes
30  30  Kriti  21.0  Bangalore  65000.0  Female    Yes
----------------------------------------------------------------------
ID          int64
Name       object
Age       float64
City       object
Salary    float64
Gender     object
Remote     object
dtype: object
----------------------------------------------------------------------
              ID        Age         Salary
count  31.000000  28.000000      29.000000
mean   15.548387  22.714286   56482.758621
std     8.659633   5.830044   21465.288740
min     1.000000  -2.000000   -5000.000000
25%     8.500000  21.000000   48000.000000
50%    16.000000  23.000000   55000.000000
75%    22.500000  25.000000   65000.000000
max    30.000000  35.000000  120000.000000
----------------------------------------------------------------------
Number of Unique cities: 4
----------------------------------------------------------------------
['Delhi' 'Mumbai' None 'Bangalore' 'Pune']
----------------------------------------------------------------------
Numbr of employees in each city
 City
Delhi        12
Mumbai        8
Pune          5
Bangalore     4
Name: count, dtype: int64
----------------------------------------------------------------------

## Level 2 : Missing Values

In [106]:
# Q9. Missing values in every column
print(df.isnull().sum())


# Q10. Rows containing at least one missing value
print(df[df.isnull().any(axis=1)])


# Q11. Number of missing Age values
print(f"Missing Age: {df['Age'].isnull().sum()}")


# Q12. Fill missing Age with mean
mean_age = df["Age"].mean()

df["Age"] = df["Age"].fillna(mean_age)

print(f"Age filled with mean: {mean_age:.2f}")


# Q13. Fill missing City
df["City"] = df["City"].fillna("Unknown")

print("Missing City values replaced with 'Unknown'.")


# Q14. Fill missing Gender
df["Gender"] = df["Gender"].fillna("Unknown")

print("Missing Gender values replaced with 'Unknown'.")


# Q15. Remove rows where Name is missing
df = df.dropna(subset=["Name"])

print(f"Rows after removing missing names: {len(df)}")


# Q16. Remove rows where all values are missing
df = df.dropna(how="all")

print(f"Rows remaining: {len(df)}")

ID        0
Name      1
Age       3
City      2
Salary    2
Gender    2
Remote    1
dtype: int64
    ID    Name   Age       City   Salary  Gender Remote
2    3   Priya   NaN      Delhi  40000.0  Female    Yes
3    4    Aman  23.0       None  60000.0    Male    Yes
4    5   Sneha  21.0  Bangalore      NaN  Female     No
5    6    None  24.0      Delhi  52000.0    Male    Yes
6    7    Riya   NaN     Mumbai  48000.0  Female    Yes
7    8   Arjun  25.0       Pune  70000.0    None     No
11  12  Anjali  23.0       None  62000.0  Female    Yes
12  13   Rohit  27.0      Delhi      NaN    Male     No
13  14   Pooja  22.0     Mumbai  45000.0    None    Yes
15  16   Meena   NaN      Delhi  50000.0  Female    Yes
26  26    Sara  21.0      Delhi  48000.0  Female   None
Missing Age: 3
Age filled with mean: 22.71
Missing City values replaced with 'Unknown'.
Missing Gender values replaced with 'Unknown'.
Rows after removing missing names: 30
Rows remaining: 30

### Level 3 — Filtering

In [109]:
# Q17. Age greater than 25
result = df[df["Age"] > 25]

print("Age > 25:")
print(result)


# Q18. Employees from Delhi
result = df[df["City"] == "Delhi"]

print("Employees from Delhi:")
print(result)


# Q19. Delhi AND salary > 50000
result = df[
    (df["City"] == "Delhi") &
    (df["Salary"] > 50000)
]

print("Delhi employees earning > ₹50,000:")
print(result)


# Q20. Delhi OR Mumbai
result = df[
    (df["City"] == "Delhi") |
    (df["City"] == "Mumbai")
]

print("Employees from Delhi or Mumbai:")
print(result)


# Q21. Salary between 40000 and 70000
result = df[
    df["Salary"].between(40000, 70000)
]

print("Salary between ₹40,000 and ₹70,000:")
print(result)


# Q22. Age between 20 and 25
result = df[
    df["Age"].between(20, 25)
]

print("Age between 20 and 25:")
print(result)


# Q23. Employees NOT from Delhi
result = df[df["City"] != "Delhi"]

print("Employees not from Delhi:")
print(result)


# Q24. Female employees earning > 50000
result = df[
    (df["Gender"] == "Female") &
    (df["Salary"] > 50000)
]

print("Female employees earning > ₹50,000:")
print(result)

Age > 25:
    ID    Name   Age       City    Salary  Gender Remote
10  11   Karan  26.0  Bangalore   80000.0    Male    Yes
12  13   Rohit  27.0      Delhi       NaN    Male     No
19  19  Simran  29.0     Mumbai   90000.0  Female    Yes
21  21   Kabir  35.0      Delhi  120000.0    Male     No
27  27     Dev  28.0  Bangalore   75000.0    Male    Yes
Employees from Delhi:
    ID     Name        Age   City    Salary  Gender Remote
0    1  Hasnain  21.000000  Delhi   45000.0    Male    Yes
2    3    Priya  22.714286  Delhi   40000.0  Female    Yes
8    9   Vikash  22.000000  Delhi   55000.0    Male    Yes
12  13    Rohit  27.000000  Delhi       NaN    Male     No
15  16    Meena  22.714286  Delhi   50000.0  Female    Yes
18  18      Raj  21.000000  Delhi   -5000.0    Male    Yes
20  20     Aman  23.000000  Delhi   60000.0    Male    Yes
21  21    Kabir  35.000000  Delhi  120000.0    Male     No
23  23     Ravi  22.000000  Delhi   55000.0       M    Yes
26  26     Sara  21.000000  Delhi   48000.0  Female   None
28  28     Isha  22.000000  Delhi   50000.0  Female     No
Delhi employees earning > ₹50,000:
    ID    Name   Age   City    Salary Gender Remote
8    9  Vikash  22.0  Delhi   55000.0   Male    Yes
20  20    Aman  23.0  Delhi   60000.0   Male    Yes
21  21   Kabir  35.0  Delhi  120000.0   Male     No
23  23    Ravi  22.0  Delhi   55000.0      M    Yes
Employees from Delhi or Mumbai:
    ID     Name        Age    City    Salary   Gender Remote
0    1  Hasnain  21.000000   Delhi   45000.0     Male    Yes
1    2    Rahul  22.000000  Mumbai   55000.0     Male     No
2    3    Priya  22.714286   Delhi   40000.0   Female    Yes
6    7     Riya  22.714286  Mumbai   48000.0   Female    Yes
8    9   Vikash  22.000000   Delhi   55000.0     Male    Yes
9   10     Neha  20.000000  Mumbai   35000.0   Female     No
12  13    Rohit  27.000000   Delhi       NaN     Male     No
13  14    Pooja  22.000000  Mumbai   45000.0  Unknown    Yes
15  16    Meena  22.714286   Delhi   50000.0   Female    Yes
18  18      Raj  21.000000   Delhi   -5000.0     Male    Yes
19  19   Simran  29.000000  Mumbai   90000.0   Female    Yes
20  20     Aman  23.000000   Delhi   60000.0     Male    Yes
21  21    Kabir  35.000000   Delhi  120000.0     Male     No
22  22    Nisha  19.000000  Mumbai   25000.0   Female    Yes
23  23     Ravi  22.000000   Delhi   55000.0        M    Yes
24  24    Pinky  24.000000  Mumbai   60000.0        F     No
26  26     Sara  21.000000   Delhi   48000.0   Female   None
28  28     Isha  22.000000   Delhi   50000.0   Female     No
29  29    Rohan  23.000000  Mumbai   55000.0     Male    Yes
Salary between ₹40,000 and ₹70,000:
    ID     Name        Age       City   Salary   Gender Remote
0    1  Hasnain  21.000000      Delhi  45000.0     Male    Yes
1    2    Rahul  22.000000     Mumbai  55000.0     Male     No
2    3    Priya  22.714286      Delhi  40000.0   Female    Yes
3    4     Aman  23.000000    Unknown  60000.0     Male    Yes
6    7     Riya  22.714286     Mumbai  48000.0   Female    Yes
7    8    Arjun  25.000000       Pune  70000.0  Unknown     No
8    9   Vikash  22.000000      Delhi  55000.0     Male    Yes
11  12   Anjali  23.000000    Unknown  62000.0   Female    Yes
13  14    Pooja  22.000000     Mumbai  45000.0  Unknown    Yes
14  15   Sameer  24.000000       Pune  58000.0     Male     No
15  16    Meena  22.714286      Delhi  50000.0   Female    Yes
16  17    Arjun  25.000000       Pune  70000.0     Male     No
17  17    Arjun  25.000000       Pune  70000.0     Male     No
20  20     Aman  23.000000      Delhi  60000.0     Male    Yes
23  23     Ravi  22.000000      Delhi  55000.0        M    Yes
24  24    Pinky  24.000000     Mumbai  60000.0        F     No
25  25    Mohit  -2.000000       Pune  45000.0     Male    Yes
26  26     Sara  21.000000      Delhi  48000.0   Female   None
28  28     Isha  22.000000      Delhi  50000.0   Female     No
29  29    Rohan  23.000000     Mumbai  55000.0     Male    Yes
30  30    Kriti  21.000000  Bangalore  65000.0   Female    Yes
Age between 20 and 25:
    ID     Name        Age       City   Salary   Gender Remote
0    1  Hasnain  21.000000      Delhi  45000.0     Male    Yes
1    2    Rahul  22.000000     Mumbai  55000.0     Male     No
2    3    Priya  22.714286      Delhi  40000.0   Female    Yes
3    4     Aman  23.000000    Unknown  60000.0     Male    Yes
4    5    Sneha  21.000000  Bangalore      NaN   Female     No
6    7     Riya  22.714286     Mumbai  48000.0   Female    Yes
7    8    Arjun  25.000000       Pune  70000.0  Unknown     No
8    9   Vikash  22.000000      Delhi  55000.0     Male    Yes
9   10     Neha  20.000000     Mumbai  35000.0   Female     No
11  12   Anjali  23.000000    Unknown  62000.0   Female    Yes
13  14    Pooja  22.000000     Mumbai  45000.0  Unknown    Yes
14  15   Sameer  24.000000       Pune  58000.0     Male     No
15  16    Meena  22.714286      Delhi  50000.0   Female    Yes
16  17    Arjun  25.000000       Pune  70000.0     Male     No
17  17    Arjun  25.000000       Pune  70000.0     Male     No
18  18      Raj  21.000000      Delhi  -5000.0     Male    Yes
20  20     Aman  23.000000      Delhi  60000.0     Male    Yes
23  23     Ravi  22.000000      Delhi  55000.0        M    Yes
24  24    Pinky  24.000000     Mumbai  60000.0        F     No
26  26     Sara  21.000000      Delhi  48000.0   Female   None
28  28     Isha  22.000000      Delhi  50000.0   Female     No
29  29    Rohan  23.000000     Mumbai  55000.0     Male    Yes
30  30    Kriti  21.000000  Bangalore  65000.0   Female    Yes
Employees not from Delhi:
    ID    Name        Age       City   Salary   Gender Remote
1    2   Rahul  22.000000     Mumbai  55000.0     Male     No
3    4    Aman  23.000000    Unknown  60000.0     Male    Yes
4    5   Sneha  21.000000  Bangalore      NaN   Female     No
6    7    Riya  22.714286     Mumbai  48000.0   Female    Yes
7    8   Arjun  25.000000       Pune  70000.0  Unknown     No
9   10    Neha  20.000000     Mumbai  35000.0   Female     No
10  11   Karan  26.000000  Bangalore  80000.0     Male    Yes
11  12  Anjali  23.000000    Unknown  62000.0   Female    Yes
13  14   Pooja  22.000000     Mumbai  45000.0  Unknown    Yes
14  15  Sameer  24.000000       Pune  58000.0     Male     No
16  17   Arjun  25.000000       Pune  70000.0     Male     No
17  17   Arjun  25.000000       Pune  70000.0     Male     No
19  19  Simran  29.000000     Mumbai  90000.0   Female    Yes
22  22   Nisha  19.000000     Mumbai  25000.0   Female    Yes
24  24   Pinky  24.000000     Mumbai  60000.0        F     No
25  25   Mohit  -2.000000       Pune  45000.0     Male    Yes
27  27     Dev  28.000000  Bangalore  75000.0     Male    Yes
29  29   Rohan  23.000000     Mumbai  55000.0     Male    Yes
30  30   Kriti  21.000000  Bangalore  65000.0   Female    Yes
Female employees earning > ₹50,000:
    ID    Name   Age       City   Salary  Gender Remote
11  12  Anjali  23.0    Unknown  62000.0  Female    Yes
19  19  Simran  29.0     Mumbai  90000.0  Female    Yes
30  30   Kriti  21.0  Bangalore  65000.0  Female    Yes

## Level 4 — Duplicates

In [112]:
# Q25. Find duplicate rows
duplicates = df[df.duplicated()]

print("Duplicate rows:")
print(duplicates)


# Q26. Count duplicate rows
count = df.duplicated().sum()

print(f"Number of duplicate rows: {count}")


# Q27. Remove duplicate rows
df = df.drop_duplicates()

print(f"Rows after removing duplicates: {len(df)}")


# Q28. Find duplicate IDs
duplicates = df[df["ID"].duplicated()]

print("Duplicate IDs:")
print(duplicates)


# Q29. Remove duplicate IDs
df = df.drop_duplicates(
    subset=["ID"],
    keep="first"
)

print("Duplicate IDs removed.")

Duplicate rows:
    ID   Name   Age  City   Salary Gender Remote
17  17  Arjun  25.0  Pune  70000.0   Male     No
Number of duplicate rows: 1
Rows after removing duplicates: 29
Duplicate IDs:
Empty DataFrame
Columns: [ID, Name, Age, City, Salary, Gender, Remote]
Index: []
Duplicate IDs removed.

## Level 5 — Invalid Data

In [115]:
# Q30. Find negative salaries
result = df[df["Salary"] < 0]

print("Negative salaries:")
print(result)


# Q31. Find negative ages
result = df[df["Age"] < 0]

print("Negative ages:")
print(result)


# Q32. Replace negative salary with NaN
df.loc[
    df["Salary"] < 0,
    "Salary"
] = np.nan

print("Negative salaries replaced with NaN.")


# Q33. Replace negative age with NaN
df.loc[
    df["Age"] < 0,
    "Age"
] = np.nan

print("Negative ages replaced with NaN.")


# Q34. Fill missing salary with median
median_salary = df["Salary"].median()

df["Salary"] = df["Salary"].fillna(
    median_salary
)

print(f"Missing salaries filled with median: ₹{median_salary:,.2f}")

Negative salaries:
    ID Name   Age   City  Salary Gender Remote
18  18  Raj  21.0  Delhi -5000.0   Male    Yes
Negative ages:
    ID   Name  Age  City   Salary Gender Remote
25  25  Mohit -2.0  Pune  45000.0   Male    Yes
Negative salaries replaced with NaN.
Negative ages replaced with NaN.
Missing salaries filled with median: ₹55,000.00

## Level 6 — Data Transformation

In [118]:
# Q35. Create Annual Salary
df["Annual_Salary"] = df["Salary"] * 12

print(df[["Name", "Salary", "Annual_Salary"]])


# Q36. Create Salary Level
def salary_level(salary):
    if salary < 50000:
        return "Low"
    elif salary <= 80000:
        return "Medium"
    else:
        return "High"


df["Salary_Level"] = df["Salary"].apply(
    salary_level
)

print(df[["Name", "Salary", "Salary_Level"]])


# Q37. Create Age Group
def age_group(age):
    if age < 22:
        return "Young"
    elif age <= 25:
        return "Adult"
    else:
        return "Senior"


df["Age_Group"] = df["Age"].apply(
    age_group
)

print(df[["Name", "Age", "Age_Group"]])


# Q38. Standardize Gender
df["Gender"] = df["Gender"].replace({
    "M": "Male",
    "F": "Female"
})

print(df["Gender"].value_counts())

       Name    Salary  Annual_Salary
0   Hasnain   45000.0       540000.0
1     Rahul   55000.0       660000.0
2     Priya   40000.0       480000.0
3      Aman   60000.0       720000.0
4     Sneha   55000.0       660000.0
6      Riya   48000.0       576000.0
7     Arjun   70000.0       840000.0
8    Vikash   55000.0       660000.0
9      Neha   35000.0       420000.0
10    Karan   80000.0       960000.0
11   Anjali   62000.0       744000.0
12    Rohit   55000.0       660000.0
13    Pooja   45000.0       540000.0
14   Sameer   58000.0       696000.0
15    Meena   50000.0       600000.0
16    Arjun   70000.0       840000.0
18      Raj   55000.0       660000.0
19   Simran   90000.0      1080000.0
20     Aman   60000.0       720000.0
21    Kabir  120000.0      1440000.0
22    Nisha   25000.0       300000.0
23     Ravi   55000.0       660000.0
24    Pinky   60000.0       720000.0
25    Mohit   45000.0       540000.0
26     Sara   48000.0       576000.0
27      Dev   75000.0       900000.0
28     Isha   50000.0       600000.0
29    Rohan   55000.0       660000.0
30    Kriti   65000.0       780000.0
       Name    Salary Salary_Level
0   Hasnain   45000.0          Low
1     Rahul   55000.0       Medium
2     Priya   40000.0          Low
3      Aman   60000.0       Medium
4     Sneha   55000.0       Medium
6      Riya   48000.0          Low
7     Arjun   70000.0       Medium
8    Vikash   55000.0       Medium
9      Neha   35000.0          Low
10    Karan   80000.0       Medium
11   Anjali   62000.0       Medium
12    Rohit   55000.0       Medium
13    Pooja   45000.0          Low
14   Sameer   58000.0       Medium
15    Meena   50000.0       Medium
16    Arjun   70000.0       Medium
18      Raj   55000.0       Medium
19   Simran   90000.0         High
20     Aman   60000.0       Medium
21    Kabir  120000.0         High
22    Nisha   25000.0          Low
23     Ravi   55000.0       Medium
24    Pinky   60000.0       Medium
25    Mohit   45000.0          Low
26     Sara   48000.0          Low
27      Dev   75000.0       Medium
28     Isha   50000.0       Medium
29    Rohan   55000.0       Medium
30    Kriti   65000.0       Medium
       Name        Age Age_Group
0   Hasnain  21.000000     Young
1     Rahul  22.000000     Adult
2     Priya  22.714286     Adult
3      Aman  23.000000     Adult
4     Sneha  21.000000     Young
6      Riya  22.714286     Adult
7     Arjun  25.000000     Adult
8    Vikash  22.000000     Adult
9      Neha  20.000000     Young
10    Karan  26.000000    Senior
11   Anjali  23.000000     Adult
12    Rohit  27.000000    Senior
13    Pooja  22.000000     Adult
14   Sameer  24.000000     Adult
15    Meena  22.714286     Adult
16    Arjun  25.000000     Adult
18      Raj  21.000000     Young
19   Simran  29.000000    Senior
20     Aman  23.000000     Adult
21    Kabir  35.000000    Senior
22    Nisha  19.000000     Young
23     Ravi  22.000000     Adult
24    Pinky  24.000000     Adult
25    Mohit        NaN    Senior
26     Sara  21.000000     Young
27      Dev  28.000000    Senior
28     Isha  22.000000     Adult
29    Rohan  23.000000     Adult
30    Kriti  21.000000     Young
Gender
Male       15
Female     12
Unknown     2
Name: count, dtype: int64

## Level 7 — Sorting

In [121]:
# Q39. Salary: Low → High
result = df.sort_values(
    by="Salary",
    ascending=True
)

print(result[["Name", "Salary"]])


# Q40. Salary: High → Low
result = df.sort_values(
    by="Salary",
    ascending=False
)

print(result[["Name", "Salary"]])


# Q41. City ascending + Salary descending
result = df.sort_values(
    by=["City", "Salary"],
    ascending=[True, False]
)

print(result[["Name", "City", "Salary"]])

       Name    Salary
22    Nisha   25000.0
9      Neha   35000.0
2     Priya   40000.0
0   Hasnain   45000.0
25    Mohit   45000.0
13    Pooja   45000.0
26     Sara   48000.0
6      Riya   48000.0
28     Isha   50000.0
15    Meena   50000.0
12    Rohit   55000.0
8    Vikash   55000.0
29    Rohan   55000.0
1     Rahul   55000.0
18      Raj   55000.0
4     Sneha   55000.0
23     Ravi   55000.0
14   Sameer   58000.0
3      Aman   60000.0
20     Aman   60000.0
24    Pinky   60000.0
11   Anjali   62000.0
30    Kriti   65000.0
16    Arjun   70000.0
7     Arjun   70000.0
27      Dev   75000.0
10    Karan   80000.0
19   Simran   90000.0
21    Kabir  120000.0
       Name    Salary
21    Kabir  120000.0
19   Simran   90000.0
10    Karan   80000.0
27      Dev   75000.0
7     Arjun   70000.0
16    Arjun   70000.0
30    Kriti   65000.0
11   Anjali   62000.0
24    Pinky   60000.0
3      Aman   60000.0
20     Aman   60000.0
14   Sameer   58000.0
8    Vikash   55000.0
4     Sneha   55000.0
23     Ravi   55000.0
12    Rohit   55000.0
1     Rahul   55000.0
18      Raj   55000.0
29    Rohan   55000.0
28     Isha   50000.0
15    Meena   50000.0
26     Sara   48000.0
6      Riya   48000.0
13    Pooja   45000.0
25    Mohit   45000.0
0   Hasnain   45000.0
2     Priya   40000.0
9      Neha   35000.0
22    Nisha   25000.0
       Name       City    Salary
10    Karan  Bangalore   80000.0
27      Dev  Bangalore   75000.0
30    Kriti  Bangalore   65000.0
4     Sneha  Bangalore   55000.0
21    Kabir      Delhi  120000.0
20     Aman      Delhi   60000.0
8    Vikash      Delhi   55000.0
12    Rohit      Delhi   55000.0
18      Raj      Delhi   55000.0
23     Ravi      Delhi   55000.0
15    Meena      Delhi   50000.0
28     Isha      Delhi   50000.0
26     Sara      Delhi   48000.0
0   Hasnain      Delhi   45000.0
2     Priya      Delhi   40000.0
19   Simran     Mumbai   90000.0
24    Pinky     Mumbai   60000.0
1     Rahul     Mumbai   55000.0
29    Rohan     Mumbai   55000.0
6      Riya     Mumbai   48000.0
13    Pooja     Mumbai   45000.0
9      Neha     Mumbai   35000.0
22    Nisha     Mumbai   25000.0
7     Arjun       Pune   70000.0
16    Arjun       Pune   70000.0
14   Sameer       Pune   58000.0
25    Mohit       Pune   45000.0
11   Anjali    Unknown   62000.0
3      Aman    Unknown   60000.0

## Level 8 — loc and iloc

In [124]:
# Q42. Delhi employees: Name, Age, Salary
result = df.loc[
    df["City"] == "Delhi",
    ["Name", "Age", "Salary"]
]

print(result)


# Q43. First 5 rows using iloc
result = df.iloc[0:5]

print(result)


# Q44. Rows 5–10 and columns 1–4
result = df.iloc[5:11, 1:5]

print(result)


# Q45. Age > 22 AND Salary > 50000
result = df.loc[
    (df["Age"] > 22) &
    (df["Salary"] > 50000)
]

print(result)

       Name        Age    Salary
0   Hasnain  21.000000   45000.0
2     Priya  22.714286   40000.0
8    Vikash  22.000000   55000.0
12    Rohit  27.000000   55000.0
15    Meena  22.714286   50000.0
18      Raj  21.000000   55000.0
20     Aman  23.000000   60000.0
21    Kabir  35.000000  120000.0
23     Ravi  22.000000   55000.0
26     Sara  21.000000   48000.0
28     Isha  22.000000   50000.0
   ID     Name        Age       City   Salary  Gender Remote  Annual_Salary  \
0   1  Hasnain  21.000000      Delhi  45000.0    Male    Yes       540000.0
1   2    Rahul  22.000000     Mumbai  55000.0    Male     No       660000.0
2   3    Priya  22.714286      Delhi  40000.0  Female    Yes       480000.0
3   4     Aman  23.000000    Unknown  60000.0    Male    Yes       720000.0
4   5    Sneha  21.000000  Bangalore  55000.0  Female     No       660000.0

  Salary_Level Age_Group
0          Low     Young
1       Medium     Adult
2          Low     Adult
3       Medium     Adult
4       Medium     Young
      Name        Age       City   Salary
6     Riya  22.714286     Mumbai  48000.0
7    Arjun  25.000000       Pune  70000.0
8   Vikash  22.000000      Delhi  55000.0
9     Neha  20.000000     Mumbai  35000.0
10   Karan  26.000000  Bangalore  80000.0
11  Anjali  23.000000    Unknown  62000.0
    ID    Name   Age       City    Salary   Gender Remote  Annual_Salary  \
3    4    Aman  23.0    Unknown   60000.0     Male    Yes       720000.0
7    8   Arjun  25.0       Pune   70000.0  Unknown     No       840000.0
10  11   Karan  26.0  Bangalore   80000.0     Male    Yes       960000.0
11  12  Anjali  23.0    Unknown   62000.0   Female    Yes       744000.0
12  13   Rohit  27.0      Delhi   55000.0     Male     No       660000.0
14  15  Sameer  24.0       Pune   58000.0     Male     No       696000.0
16  17   Arjun  25.0       Pune   70000.0     Male     No       840000.0
19  19  Simran  29.0     Mumbai   90000.0   Female    Yes      1080000.0
20  20    Aman  23.0      Delhi   60000.0     Male    Yes       720000.0
21  21   Kabir  35.0      Delhi  120000.0     Male     No      1440000.0
24  24   Pinky  24.0     Mumbai   60000.0   Female     No       720000.0
27  27     Dev  28.0  Bangalore   75000.0     Male    Yes       900000.0
29  29   Rohan  23.0     Mumbai   55000.0     Male    Yes       660000.0

   Salary_Level Age_Group
3        Medium     Adult
7        Medium     Adult
10       Medium    Senior
11       Medium     Adult
12       Medium    Senior
14       Medium     Adult
16       Medium     Adult
19         High    Senior
20       Medium     Adult
21         High    Senior
24       Medium     Adult
27       Medium    Senior
29       Medium     Adult

## Level 9 — GroupBy

In [127]:
# Q46. Average salary by city
result = df.groupby("City")["Salary"].mean()

print("Average Salary by City:")

for city, salary in result.items():
    print(f"{city:<12} ₹{salary:,.2f}")


# Q47. Maximum salary by city
result = df.groupby("City")["Salary"].max()

print("\nMaximum Salary by City:")

for city, salary in result.items():
    print(f"{city:<12} ₹{salary:,.0f}")


# Q48. Minimum salary by city
result = df.groupby("City")["Salary"].min()

print("\nMinimum Salary by City:")

for city, salary in result.items():
    print(f"{city:<12} ₹{salary:,.0f}")


# Q49. Employee count by city
result = df["City"].value_counts()

print("\nEmployees by City:")

for city, count in result.items():
    print(f"{city:<12} {count} employees")


# Q50. Average age by gender
result = df.groupby("Gender")["Age"].mean()

print("\nAverage Age by Gender:")

for gender, age in result.items():
    print(f"{gender:<12} {age:.2f} years")


# Q51. Total salary by city
result = df.groupby("City")["Salary"].sum()

print("\nTotal Salary by City:")

for city, salary in result.items():
    print(f"{city:<12} ₹{salary:,.0f}")


# Q52. City with highest average salary
result = df.groupby("City")["Salary"].mean()

city = result.idxmax()
salary = result.max()

print(
    f"\nHighest average salary: "
    f"{city} → ₹{salary:,.2f}"
)

Average Salary by City:
Bangalore    ₹68,750.00
Delhi        ₹57,545.45
Mumbai       ₹51,625.00
Pune         ₹60,750.00
Unknown      ₹61,000.00

Maximum Salary by City:
Bangalore    ₹80,000
Delhi        ₹120,000
Mumbai       ₹90,000
Pune         ₹70,000
Unknown      ₹62,000

Minimum Salary by City:
Bangalore    ₹55,000
Delhi        ₹40,000
Mumbai       ₹25,000
Pune         ₹45,000
Unknown      ₹60,000

Employees by City:
Delhi        11 employees
Mumbai       8 employees
Bangalore    4 employees
Pune         4 employees
Unknown      2 employees

Average Age by Gender:
Female       22.35 years
Male         24.43 years
Unknown      23.50 years

Total Salary by City:
Bangalore    ₹275,000
Delhi        ₹633,000
Mumbai       ₹413,000
Pune         ₹243,000
Unknown      ₹122,000

Highest average salary: Bangalore → ₹68,750.00