In [1]:
import pandas as pd
import numpy as np

data = [
    [101, "Hasnain Khan", 21, "CSE", "Delhi", 85, 78, "Male", "2025-06-15"],
    [102, "Rahul Sharma", 22, "ECE", "Mumbai", 72, 81, "Male", "2025-07-10"],
    [103, "Priya Singh", 20, "CSE", "Delhi", 91, 88, "Female", "2025-06-20"],
    [104, "Aman Verma", 23, "IT", "Pune", 65, 70, "Male", "2025-08-05"],
    [105, "Sneha Gupta", 21, "CSE", "Mumbai", 88, 92, "Female", "2025-06-25"],
    [106, "Arjun Mehta", 22, "ECE", "Delhi", 76, 69, "Male", "2025-07-15"],
    [107, "Riya Kapoor", 20, "IT", "Bangalore", 95, 90, "Female", "2025-06-18"],
    [108, "Vikas Yadav", 24, "CSE", "Pune", 60, 64, "Male", "2025-08-10"],
    [109, "Neha Joshi", 21, "ECE", "Mumbai", 82, 85, "Female", "2025-07-20"],
    [110, "Karan Malhotra", 23, "IT", "Delhi", 74, 79, "Male", "2025-08-12"],
    [111, "Anjali Rao", 20, "CSE", "Bangalore", 89, 94, "Female", "2025-06-22"],
    [112, "Rohit Kumar", 22, "ECE", "Pune", 68, 72, "Male", "2025-07-25"],
    [113, "Pooja Sharma", 21, "IT", "Mumbai", 93, 87, "Female", "2025-08-01"],
    [114, "Sameer Ali", 24, "CSE", "Delhi", 55, 61, "Male", "2025-08-15"],
    [115, "Meena Patel", 22, "ECE", "Bangalore", 80, 83, "Female", "2025-07-28"],
]

columns = [
    "Student_ID",
    "Name",
    "Age",
    "Branch",
    "City",
    "Maths",
    "Programming",
    "Gender",
    "Joining_Date"
]

df = pd.DataFrame(data, columns=columns)

print(df)

    Student_ID            Name  Age Branch       City  Maths  Programming  \
0          101    Hasnain Khan   21    CSE      Delhi     85           78
1          102    Rahul Sharma   22    ECE     Mumbai     72           81
2          103     Priya Singh   20    CSE      Delhi     91           88
3          104      Aman Verma   23     IT       Pune     65           70
4          105     Sneha Gupta   21    CSE     Mumbai     88           92
5          106     Arjun Mehta   22    ECE      Delhi     76           69
6          107     Riya Kapoor   20     IT  Bangalore     95           90
7          108     Vikas Yadav   24    CSE       Pune     60           64
8          109      Neha Joshi   21    ECE     Mumbai     82           85
9          110  Karan Malhotra   23     IT      Delhi     74           79
10         111      Anjali Rao   20    CSE  Bangalore     89           94
11         112     Rohit Kumar   22    ECE       Pune     68           72
12         113    Pooja Sharma   21     IT     Mumbai     93           87
13         114      Sameer Ali   24    CSE      Delhi     55           61
14         115     Meena Patel   22    ECE  Bangalore     80           83

    Gender Joining_Date
0     Male   2025-06-15
1     Male   2025-07-10
2   Female   2025-06-20
3     Male   2025-08-05
4   Female   2025-06-25
5     Male   2025-07-15
6   Female   2025-06-18
7     Male   2025-08-10
8   Female   2025-07-20
9     Male   2025-08-12
10  Female   2025-06-22
11    Male   2025-07-25
12  Female   2025-08-01
13    Male   2025-08-15
14  Female   2025-07-28

In [3]:
df

,Student_ID,Name,Age,Branch,City,Maths,Programming,Gender,Joining_Date
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15
1,102,Rahul Sharma,22,ECE,Mumbai,72,81,Male,2025-07-10
2,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05
4,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15
6,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18
7,108,Vikas Yadav,24,CSE,Pune,60,64,Male,2025-08-10
8,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12
10,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22
11,112,Rohit Kumar,22,ECE,Pune,68,72,Male,2025-07-25
12,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01
13,114,Sameer Ali,24,CSE,Delhi,55,61,Male,2025-08-15
14,115,Meena Patel,22,ECE,Bangalore,80,83,Female,2025-07-28

## Level 1 : Rename

In [6]:
df = df.rename(columns={
    "Maths": "Math_Score",
    "Programming": "Programming_Score"
})

print(df.head())

   Student_ID          Name  Age Branch    City  Math_Score  \
0         101  Hasnain Khan   21    CSE   Delhi          85
1         102  Rahul Sharma   22    ECE  Mumbai          72
2         103   Priya Singh   20    CSE   Delhi          91
3         104    Aman Verma   23     IT    Pune          65
4         105   Sneha Gupta   21    CSE  Mumbai          88

   Programming_Score  Gender Joining_Date
0                 78    Male   2025-06-15
1                 81    Male   2025-07-10
2                 88  Female   2025-06-20
3                 70    Male   2025-08-05
4                 92  Female   2025-06-25

In [10]:
df.rename(columns={
    "Student_ID": "ID",
    "Joining_Date": "Date"
}, inplace=True)

In [14]:
df.columns

Index(['ID', 'Name', 'Age', 'Branch', 'City', 'Math_Score',
       'Programming_Score', 'Gender', 'Date'],
      dtype='object')

## Level 2 — astype()

In [19]:
df.dtypes

ID                    int64
Name                 object
Age                   int64
Branch               object
City                 object
Math_Score            int64
Programming_Score     int64
Gender               object
Date                 object
dtype: object

In [25]:
# make id string
df["ID"]=df["ID"].astype(str)

In [27]:
print(df["ID"].dtype)

object

In [29]:
df["ID"] = df["ID"].astype(int)

## Level 3 — map()

In [32]:
df["Gender_Code"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})

In [34]:
print(
    df[["Name", "Gender", "Gender_Code"]]
)

              Name  Gender  Gender_Code
0     Hasnain Khan    Male            1
1     Rahul Sharma    Male            1
2      Priya Singh  Female            0
3       Aman Verma    Male            1
4      Sneha Gupta  Female            0
5      Arjun Mehta    Male            1
6      Riya Kapoor  Female            0
7      Vikas Yadav    Male            1
8       Neha Joshi  Female            0
9   Karan Malhotra    Male            1
10      Anjali Rao  Female            0
11     Rohit Kumar    Male            1
12    Pooja Sharma  Female            0
13      Sameer Ali    Male            1
14     Meena Patel  Female            0

## Level 4 — apply()

In [37]:
df["Average_Score"] = df[
    ["Math_Score", "Programming_Score"]
].mean(axis=1)

In [39]:
df["Average_Score"]

0     81.5
1     76.5
2     89.5
3     67.5
4     90.0
5     72.5
6     92.5
7     62.0
8     83.5
9     76.5
10    91.5
11    70.0
12    90.0
13    58.0
14    81.5
Name: Average_Score, dtype: float64

In [41]:
def performance(score):

    if score >= 90:
        return "Excellent"

    elif score >= 75:
        return "Good"

    elif score >= 60:
        return "Average"

    else:
        return "Poor"

In [43]:
df["Performance"] = df["Average_Score"].apply(
    performance
)

In [49]:

    df[
        ["Name", "Average_Score", "Performance"]
    ]

              Name  Average_Score Performance
0     Hasnain Khan           81.5        Good
1     Rahul Sharma           76.5        Good
2      Priya Singh           89.5        Good
3       Aman Verma           67.5     Average
4      Sneha Gupta           90.0   Excellent
5      Arjun Mehta           72.5     Average
6      Riya Kapoor           92.5   Excellent
7      Vikas Yadav           62.0     Average
8       Neha Joshi           83.5        Good
9   Karan Malhotra           76.5        Good
10      Anjali Rao           91.5   Excellent
11     Rohit Kumar           70.0     Average
12    Pooja Sharma           90.0   Excellent
13      Sameer Ali           58.0        Poor
14     Meena Patel           81.5        Good

## Level 5 — agg()

In [52]:
result = df["Math_Score"].agg([
    "mean",
    "max",
    "min"
])

print(result)

mean    78.2
max     95.0
min     55.0
Name: Math_Score, dtype: float64

In [54]:
result = df[
    ["Math_Score", "Programming_Score"]
].agg([
    "mean",
    "max",
    "min"
])

print(result)

      Math_Score  Programming_Score
mean        78.2          79.533333
max         95.0          94.000000
min         55.0          61.000000

## Level 6 — groupby() + agg()

In [57]:
result = df.groupby("Branch")["Average_Score"].agg([
    "mean",
    "max",
    "min",
    "count"
])

print(result)

          mean   max   min  count
Branch
CSE     78.750  91.5  58.0      6
ECE     76.800  83.5  70.0      5
IT      81.625  92.5  67.5      4

## Level 7 — Multiple GroupBy Columns

In [60]:
result = df.groupby(
    ["Branch", "Gender"]
)["Average_Score"].mean()

print(result)

Branch  Gender
CSE     Female    90.333333
        Male      67.166667
ECE     Female    82.500000
        Male      73.000000
IT      Female    91.250000
        Male      72.000000
Name: Average_Score, dtype: float64

In [62]:
result = df.groupby(
    ["Branch", "Gender"]
)["Average_Score"].agg([
    "mean",
    "max",
    "min",
    "count"
])

print(result)

                    mean   max   min  count
Branch Gender
CSE    Female  90.333333  91.5  89.5      3
       Male    67.166667  81.5  58.0      3
ECE    Female  82.500000  83.5  81.5      2
       Male    73.000000  76.5  70.0      3
IT     Female  91.250000  92.5  90.0      2
       Male    72.000000  76.5  67.5      2

## Level 8 — merge()

In [69]:
scholarship_data = [
    [101, 50000],
    [103, 75000],
    [105, 60000],
    [107, 80000],
    [109, 45000],
    [111, 90000],
    [113, 70000]
]

scholarship_df = pd.DataFrame(
    scholarship_data,
    columns=["ID", "Scholarship"]
)

scholarship_df

    ID  Scholarship
0  101        50000
1  103        75000
2  105        60000
3  107        80000
4  109        45000
5  111        90000
6  113        70000

In [75]:
result = pd.merge(
    df,
    scholarship_df,
    on="ID",
    how="left"
)
"""
Why left?
Because we want to keep every student, even if they don't have a scholarship.
"""
result

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance,Scholarship
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good,50000.0
1,102,Rahul Sharma,22,ECE,Mumbai,72,81,Male,2025-07-10,1,76.5,Good,NaN
2,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good,75000.0
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average,NaN
4,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent,60000.0
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15,1,72.5,Average,NaN
6,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18,0,92.5,Excellent,80000.0
7,108,Vikas Yadav,24,CSE,Pune,60,64,Male,2025-08-10,1,62.0,Average,NaN
8,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good,45000.0
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12,1,76.5,Good,NaN
10,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent,90000.0
11,112,Rohit Kumar,22,ECE,Pune,68,72,Male,2025-07-25,1,70.0,Average,NaN
12,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent,70000.0
13,114,Sameer Ali,24,CSE,Delhi,55,61,Male,2025-08-15,1,58.0,Poor,NaN
14,115,Meena Patel,22,ECE,Bangalore,80,83,Female,2025-07-28,0,81.5,Good,NaN

## Level 9 — Different Types of Merge

In [80]:
# inner : Only students present in both DataFrames
pd.merge(
    df,
    scholarship_df,
    on="ID",
    how="inner"
)

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance,Scholarship
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good,50000
1,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good,75000
2,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent,60000
3,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18,0,92.5,Excellent,80000
4,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good,45000
5,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent,90000
6,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent,70000

In [82]:
# left : Everything from df.
pd.merge(
    df,
    scholarship_df,
    on="ID",
    how="left"
)

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance,Scholarship
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good,50000.0
1,102,Rahul Sharma,22,ECE,Mumbai,72,81,Male,2025-07-10,1,76.5,Good,NaN
2,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good,75000.0
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average,NaN
4,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent,60000.0
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15,1,72.5,Average,NaN
6,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18,0,92.5,Excellent,80000.0
7,108,Vikas Yadav,24,CSE,Pune,60,64,Male,2025-08-10,1,62.0,Average,NaN
8,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good,45000.0
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12,1,76.5,Good,NaN
10,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent,90000.0
11,112,Rohit Kumar,22,ECE,Pune,68,72,Male,2025-07-25,1,70.0,Average,NaN
12,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent,70000.0
13,114,Sameer Ali,24,CSE,Delhi,55,61,Male,2025-08-15,1,58.0,Poor,NaN
14,115,Meena Patel,22,ECE,Bangalore,80,83,Female,2025-07-28,0,81.5,Good,NaN

In [84]:
# Right : everything from scholarship_df
pd.merge(
    df,
    scholarship_df,
    on="ID",
    how="right"
)

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance,Scholarship
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good,50000
1,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good,75000
2,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent,60000
3,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18,0,92.5,Excellent,80000
4,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good,45000
5,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent,90000
6,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent,70000

In [86]:
# outer : Everything from both.
pd.merge(
    df,
    scholarship_df,
    on="ID",
    how="outer"
)

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance,Scholarship
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good,50000.0
1,102,Rahul Sharma,22,ECE,Mumbai,72,81,Male,2025-07-10,1,76.5,Good,NaN
2,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good,75000.0
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average,NaN
4,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent,60000.0
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15,1,72.5,Average,NaN
6,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18,0,92.5,Excellent,80000.0
7,108,Vikas Yadav,24,CSE,Pune,60,64,Male,2025-08-10,1,62.0,Average,NaN
8,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good,45000.0
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12,1,76.5,Good,NaN
10,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent,90000.0
11,112,Rohit Kumar,22,ECE,Pune,68,72,Male,2025-07-25,1,70.0,Average,NaN
12,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent,70000.0
13,114,Sameer Ali,24,CSE,Delhi,55,61,Male,2025-08-15,1,58.0,Poor,NaN
14,115,Meena Patel,22,ECE,Bangalore,80,83,Female,2025-07-28,0,81.5,Good,NaN

## Level 10 — concat()

In [89]:
semester_1 = df.iloc[:8]

semester_2 = df.iloc[8:]

In [91]:
semester_1

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good
1,102,Rahul Sharma,22,ECE,Mumbai,72,81,Male,2025-07-10,1,76.5,Good
2,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average
4,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15,1,72.5,Average
6,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18,0,92.5,Excellent
7,108,Vikas Yadav,24,CSE,Pune,60,64,Male,2025-08-10,1,62.0,Average

In [93]:
semester_2

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance
8,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12,1,76.5,Good
10,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent
11,112,Rohit Kumar,22,ECE,Pune,68,72,Male,2025-07-25,1,70.0,Average
12,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent
13,114,Sameer Ali,24,CSE,Delhi,55,61,Male,2025-08-15,1,58.0,Poor
14,115,Meena Patel,22,ECE,Bangalore,80,83,Female,2025-07-28,0,81.5,Good

In [97]:
# combined
combined = pd.concat(
    [semester_1, semester_2],
    ignore_index=True
)

combined

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good
1,102,Rahul Sharma,22,ECE,Mumbai,72,81,Male,2025-07-10,1,76.5,Good
2,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average
4,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15,1,72.5,Average
6,107,Riya Kapoor,20,IT,Bangalore,95,90,Female,2025-06-18,0,92.5,Excellent
7,108,Vikas Yadav,24,CSE,Pune,60,64,Male,2025-08-10,1,62.0,Average
8,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12,1,76.5,Good
10,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent
11,112,Rohit Kumar,22,ECE,Pune,68,72,Male,2025-07-25,1,70.0,Average
12,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent
13,114,Sameer Ali,24,CSE,Delhi,55,61,Male,2025-08-15,1,58.0,Poor
14,115,Meena Patel,22,ECE,Bangalore,80,83,Female,2025-07-28,0,81.5,Good

## Level 11 — isin()

In [103]:
result = df[
    df["City"].isin([
        "Delhi",
        "Mumbai",
        "Pune"
    ])
]

result

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good
1,102,Rahul Sharma,22,ECE,Mumbai,72,81,Male,2025-07-10,1,76.5,Good
2,103,Priya Singh,20,CSE,Delhi,91,88,Female,2025-06-20,0,89.5,Good
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average
4,105,Sneha Gupta,21,CSE,Mumbai,88,92,Female,2025-06-25,0,90.0,Excellent
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15,1,72.5,Average
7,108,Vikas Yadav,24,CSE,Pune,60,64,Male,2025-08-10,1,62.0,Average
8,109,Neha Joshi,21,ECE,Mumbai,82,85,Female,2025-07-20,0,83.5,Good
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12,1,76.5,Good
11,112,Rohit Kumar,22,ECE,Pune,68,72,Male,2025-07-25,1,70.0,Average
12,113,Pooja Sharma,21,IT,Mumbai,93,87,Female,2025-08-01,0,90.0,Excellent
13,114,Sameer Ali,24,CSE,Delhi,55,61,Male,2025-08-15,1,58.0,Poor

In [107]:
# not in
result = df[
    ~df["City"].isin([
        "Delhi",
        "Mumbai"
    ])
]

print(result)

     ID         Name  Age Branch       City  Math_Score  Programming_Score  \
3   104   Aman Verma   23     IT       Pune          65                 70
6   107  Riya Kapoor   20     IT  Bangalore          95                 90
7   108  Vikas Yadav   24    CSE       Pune          60                 64
10  111   Anjali Rao   20    CSE  Bangalore          89                 94
11  112  Rohit Kumar   22    ECE       Pune          68                 72
14  115  Meena Patel   22    ECE  Bangalore          80                 83

    Gender        Date  Gender_Code  Average_Score Performance
3     Male  2025-08-05            1           67.5     Average
6   Female  2025-06-18            0           92.5   Excellent
7     Male  2025-08-10            1           62.0     Average
10  Female  2025-06-22            0           91.5   Excellent
11    Male  2025-07-25            1           70.0     Average
14  Female  2025-07-28            0           81.5        Good

## Level 12 — query()

In [110]:
result = df.query(
    "Age > 21"
)

print(result)

     ID            Name  Age Branch       City  Math_Score  Programming_Score  \
1   102    Rahul Sharma   22    ECE     Mumbai          72                 81
3   104      Aman Verma   23     IT       Pune          65                 70
5   106     Arjun Mehta   22    ECE      Delhi          76                 69
7   108     Vikas Yadav   24    CSE       Pune          60                 64
9   110  Karan Malhotra   23     IT      Delhi          74                 79
11  112     Rohit Kumar   22    ECE       Pune          68                 72
13  114      Sameer Ali   24    CSE      Delhi          55                 61
14  115     Meena Patel   22    ECE  Bangalore          80                 83

    Gender        Date  Gender_Code  Average_Score Performance
1     Male  2025-07-10            1           76.5        Good
3     Male  2025-08-05            1           67.5     Average
5     Male  2025-07-15            1           72.5     Average
7     Male  2025-08-10            1           62.0     Average
9     Male  2025-08-12            1           76.5        Good
11    Male  2025-07-25            1           70.0     Average
13    Male  2025-08-15            1           58.0        Poor
14  Female  2025-07-28            0           81.5        Good

In [112]:
# multiple conditions
result = df.query(
    "Age > 21 and Math_Score > 75"
)

print(result)

     ID         Name  Age Branch       City  Math_Score  Programming_Score  \
5   106  Arjun Mehta   22    ECE      Delhi          76                 69
14  115  Meena Patel   22    ECE  Bangalore          80                 83

    Gender        Date  Gender_Code  Average_Score Performance
5     Male  2025-07-15            1           72.5     Average
14  Female  2025-07-28            0           81.5        Good

## Level 13 — String Operations

In [115]:
df["Name"].str.upper()

0       HASNAIN KHAN
1       RAHUL SHARMA
2        PRIYA SINGH
3         AMAN VERMA
4        SNEHA GUPTA
5        ARJUN MEHTA
6        RIYA KAPOOR
7        VIKAS YADAV
8         NEHA JOSHI
9     KARAN MALHOTRA
10        ANJALI RAO
11       ROHIT KUMAR
12      POOJA SHARMA
13        SAMEER ALI
14       MEENA PATEL
Name: Name, dtype: object

In [117]:
df["Name"].str.lower()

0       hasnain khan
1       rahul sharma
2        priya singh
3         aman verma
4        sneha gupta
5        arjun mehta
6        riya kapoor
7        vikas yadav
8         neha joshi
9     karan malhotra
10        anjali rao
11       rohit kumar
12      pooja sharma
13        sameer ali
14       meena patel
Name: Name, dtype: object

In [119]:
df["Name"].str.len()

0     12
1     12
2     11
3     10
4     11
5     11
6     11
7     11
8     10
9     14
10    10
11    11
12    12
13    10
14    11
Name: Name, dtype: int64

In [123]:
result = df[
    df["Name"].str.startswith("A")
]

result

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average
5,106,Arjun Mehta,22,ECE,Delhi,76,69,Male,2025-07-15,1,72.5,Average
10,111,Anjali Rao,20,CSE,Bangalore,89,94,Female,2025-06-22,0,91.5,Excellent

In [127]:
result = df[
    df["Name"].str.contains("an")
]

result

,ID,Name,Age,Branch,City,Math_Score,Programming_Score,Gender,Date,Gender_Code,Average_Score,Performance
0,101,Hasnain Khan,21,CSE,Delhi,85,78,Male,2025-06-15,1,81.5,Good
3,104,Aman Verma,23,IT,Pune,65,70,Male,2025-08-05,1,67.5,Average
9,110,Karan Malhotra,23,IT,Delhi,74,79,Male,2025-08-12,1,76.5,Good

In [129]:
df["Name"] = df["Name"].str.strip()

In [131]:
# extract first name
df["First_Name"] = (
    df["Name"]
    .str.split()
    .str[0]
)

print(df[["Name", "First_Name"]])

              Name First_Name
0     Hasnain Khan    Hasnain
1     Rahul Sharma      Rahul
2      Priya Singh      Priya
3       Aman Verma       Aman
4      Sneha Gupta      Sneha
5      Arjun Mehta      Arjun
6      Riya Kapoor       Riya
7      Vikas Yadav      Vikas
8       Neha Joshi       Neha
9   Karan Malhotra      Karan
10      Anjali Rao     Anjali
11     Rohit Kumar      Rohit
12    Pooja Sharma      Pooja
13      Sameer Ali     Sameer
14     Meena Patel      Meena

## Level 14 — Datetime

In [134]:
df["Date"]

0     2025-06-15
1     2025-07-10
2     2025-06-20
3     2025-08-05
4     2025-06-25
5     2025-07-15
6     2025-06-18
7     2025-08-10
8     2025-07-20
9     2025-08-12
10    2025-06-22
11    2025-07-25
12    2025-08-01
13    2025-08-15
14    2025-07-28
Name: Date, dtype: object

In [138]:
df["Date"] = pd.to_datetime(
    df["Date"]
)

In [140]:
df["Date"]

0    2025-06-15
1    2025-07-10
2    2025-06-20
3    2025-08-05
4    2025-06-25
5    2025-07-15
6    2025-06-18
7    2025-08-10
8    2025-07-20
9    2025-08-12
10   2025-06-22
11   2025-07-25
12   2025-08-01
13   2025-08-15
14   2025-07-28
Name: Date, dtype: datetime64[ns]

In [142]:
df["Date"].dt.year

0     2025
1     2025
2     2025
3     2025
4     2025
5     2025
6     2025
7     2025
8     2025
9     2025
10    2025
11    2025
12    2025
13    2025
14    2025
Name: Date, dtype: int32

In [144]:
df["Date"].dt.day_name()

0        Sunday
1      Thursday
2        Friday
3       Tuesday
4     Wednesday
5       Tuesday
6     Wednesday
7        Sunday
8        Sunday
9       Tuesday
10       Sunday
11       Friday
12       Friday
13       Friday
14       Monday
Name: Date, dtype: object

In [146]:
df["Joining_Year"] = df["Date"].dt.year

df["Joining_Month"] = df["Date"].dt.month

df["Joining_Day"] = df["Date"].dt.day

## Level 15 — pivot_table()

In [151]:
result = pd.pivot_table(
    df,
    values="Average_Score",
    index="Branch",
    columns="Gender",
    aggfunc="mean"
)

result

Gender     Female       Male
Branch
CSE     90.333333  67.166667
ECE     82.500000  73.000000
IT      91.250000  72.000000

## Level 16 — melt()

In [155]:
# melt() changes data from wide → long format.
marks = df[
    ["Name", "Math_Score", "Programming_Score"]
]


marks

              Name  Math_Score  Programming_Score
0     Hasnain Khan          85                 78
1     Rahul Sharma          72                 81
2      Priya Singh          91                 88
3       Aman Verma          65                 70
4      Sneha Gupta          88                 92
5      Arjun Mehta          76                 69
6      Riya Kapoor          95                 90
7      Vikas Yadav          60                 64
8       Neha Joshi          82                 85
9   Karan Malhotra          74                 79
10      Anjali Rao          89                 94
11     Rohit Kumar          68                 72
12    Pooja Sharma          93                 87
13      Sameer Ali          55                 61
14     Meena Patel          80                 83

In [159]:
long_df = pd.melt(
    marks,
    id_vars=["Name"],
    var_name="Subject",
    value_name="Score"
)
long_df

              Name            Subject  Score
0     Hasnain Khan         Math_Score     85
1     Rahul Sharma         Math_Score     72
2      Priya Singh         Math_Score     91
3       Aman Verma         Math_Score     65
4      Sneha Gupta         Math_Score     88
5      Arjun Mehta         Math_Score     76
6      Riya Kapoor         Math_Score     95
7      Vikas Yadav         Math_Score     60
8       Neha Joshi         Math_Score     82
9   Karan Malhotra         Math_Score     74
10      Anjali Rao         Math_Score     89
11     Rohit Kumar         Math_Score     68
12    Pooja Sharma         Math_Score     93
13      Sameer Ali         Math_Score     55
14     Meena Patel         Math_Score     80
15    Hasnain Khan  Programming_Score     78
16    Rahul Sharma  Programming_Score     81
17     Priya Singh  Programming_Score     88
18      Aman Verma  Programming_Score     70
19     Sneha Gupta  Programming_Score     92
20     Arjun Mehta  Programming_Score     69
21     Riya Kapoor  Programming_Score     90
22     Vikas Yadav  Programming_Score     64
23      Neha Joshi  Programming_Score     85
24  Karan Malhotra  Programming_Score     79
25      Anjali Rao  Programming_Score     94
26     Rohit Kumar  Programming_Score     72
27    Pooja Sharma  Programming_Score     87
28      Sameer Ali  Programming_Score     61
29     Meena Patel  Programming_Score     83